In [2]:
from batcher import batcher
import numpy as np

In [44]:
X= np.random.rand(3,10)

In [45]:
test = batcher(X, batch_size = 1)

In [46]:
next(test)

array([[0.87208989],
       [0.62275709],
       [0.3102848 ]])

In [47]:
X

array([[0.87208989, 0.21240843, 0.14157953, 0.09294389, 0.40004344,
        0.7208221 , 0.41221292, 0.28936197, 0.76983513, 0.17222133],
       [0.62275709, 0.47881621, 0.83895871, 0.86615087, 0.98586928,
        0.4553422 , 0.08302474, 0.04409552, 0.34180352, 0.90054731],
       [0.3102848 , 0.92307226, 0.03091593, 0.58641181, 0.99277143,
        0.51165397, 0.09850282, 0.74827928, 0.51922306, 0.93957816]])

In [52]:
X[:,0]

array([0.87208989, 0.62275709, 0.3102848 ])