In [2]:
from main_class import *
from layers import *
from loss_functions import *

In [3]:

#Initialization debugged

np.random.seed(1)

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)
md.add(Dense(4, input_shape=(3,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(1))
md.add(Activation('sigmoid'))

print(md.layers[0].W,'\n\n' , md.layers[2].W)

[[ 0.93781623 -0.35319773 -0.3049401 ]
 [-0.61947872  0.49964333 -1.32879399]
 [ 1.00736754 -0.43948301  0.18419731]
 [-0.14397405  0.84414841 -1.18942279]] 

 [[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.0862141  -0.43892921  0.02110687  0.29140761]]


In [36]:
np.random.seed(1)
X= np.random.uniform(0, 1, (3,1))
X

array([[4.17022005e-01],
       [7.20324493e-01],
       [1.14374817e-04]])

In [37]:
 AL=md._forward(X)
AL

array([[0.49089174]])

In [32]:
md._backward(AL)

In [33]:
print(md.layers[2].W)

[[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.08612148 -0.43886054  0.02117708  0.29177911]]


In [34]:
print(md.layers[4].dW)

[[0.        0.0129995]]


In [35]:
Y= np.array([[1]])
md.train_on_batch(X,Y)

(0.7139889690044866, 1.0)