In [1]:
from main_class import *
from layers import *
from loss_functions import *

In [8]:

#Initialization debugged

np.random.seed(1)

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)
md.add(Dense(4, input_shape=(3,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(1))
md.add(Activation('sigmoid'))

print(md.layers[0].W,'\n\n' , md.layers[2].W)

[[ 0.93781623 -0.35319773 -0.3049401 ]
 [-0.61947872  0.49964333 -1.32879399]
 [ 1.00736754 -0.43948301  0.18419731]
 [-0.14397405  0.84414841 -1.18942279]] 

 [[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.0862141  -0.43892921  0.02110687  0.29140761]]


In [ ]:
np.random.seed(1)

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)
md.add(Dense(5, input_shape=(3,), initializer = 'ng'))
md.add(Activation('relu'))
md.add(Dense(2))
md.add(Activation('sigmoid'))

print(md.layers[0].W)

In [9]:
 md.layers[0].input_shape , md.layers[0].n_units ,md.layers[0].trainable 


((3,), 5, True)

In [10]:
 md.layers[1].input_shape 

(5,)

In [11]:
 md.layers[2].input_shape , md.layers[2].n_units 

((5,), 2)

In [12]:
print(md.layers[2].W)

[[ 0.53229464  0.5580581  -0.5868361  -0.65187498 -0.4669303 ]
 [ 0.53477426 -0.56802335 -0.11157067  0.64755358  0.0469028 ]]


In [13]:
md.layers[0].layer_input

In [14]:
X= np.random.uniform(0, 1, (3,1))
X

array([[0.69187711],
       [0.31551563],
       [0.68650093]])

In [15]:
Y= np.array([[1],[0]])
Y

array([[1],
       [0]])

In [16]:
 AL=md._forward(X)
AL

array([[0.43373157],
       [0.52144318]])

In [17]:
md._backward(AL)

In [19]:
print(md.layers[2].W)

[[ 0.53209161  0.5580581  -0.58725988 -0.65187498 -0.4670854 ]
 [ 0.53452626 -0.56802335 -0.1120883   0.64755358  0.04671334]]


In [14]:
print(md.layers[4].dW)

[[0.00150003 0.00441871 0.        ]
 [0.0015089  0.00444483 0.        ]]


In [20]:
md.train_on_batch(X,Y)

(0.7863979089462562, 1.0)