In [1]:
from main_class import *
from layers import *
from loss_functions import *

In [2]:

#Initialization debugged



n_x = 3     # num_px * num_px * 3
n_h1 = 4
n_h2 = 7
n_y = 1

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)

md.add(Dense(n_h1, input_shape=(n_x,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_y, initializer = 'ng'))
md.add(Activation('sigmoid'))

print(md.layers[0].W,'\n\n' , md.layers[2].W)
#md.layers[2].W=np.array([[ 0.81217268, -0.30587821, -0.26408588, -0.53648431]])

[[ 0.93781623 -0.35319773 -0.3049401 ]
 [-0.61947872  0.49964333 -1.32879399]
 [ 1.00736754 -0.43948301  0.18419731]
 [-0.14397405  0.84414841 -1.18942279]] 

 [[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.0862141  -0.43892921  0.02110687  0.29140761]
 [-0.55030959  0.57236185  0.45079536  0.25124717]
 [ 0.45042797 -0.34186393 -0.06144511 -0.46788472]
 [-0.13394404  0.26517773 -0.34583038 -0.19837676]
 [-0.34358635 -0.42260282 -0.33562307 -0.0063323 ]
 [-0.55865517  0.11720785  0.82990109  0.37102208]]


In [3]:
np.random.seed(1)
X= np.random.uniform(0, 1, (n_x,1))
X

array([[4.17022005e-01],
       [7.20324493e-01],
       [1.14374817e-04]])

In [4]:
 AL=md._forward(X)
AL

array([[0.48340483]])

In [5]:
md._backward(AL)

In [6]:
print(md.layers[2].W)

[[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.0861726  -0.4388984   0.02113833  0.29157403]
 [-0.55027465  0.57238779  0.45082183  0.25138725]
 [ 0.45042797 -0.34186393 -0.06144511 -0.46788472]
 [-0.13394404  0.26517773 -0.34583038 -0.19837676]
 [-0.34358635 -0.42260282 -0.33562307 -0.0063323 ]
 [-0.5586641   0.11720122  0.82989432  0.37098629]]


In [34]:
print(md.layers[4].dW)

[[0.        0.0129995]]


In [35]:
Y= np.array([[1]])
md.train_on_batch(X,Y)

(0.7139889690044866, 1.0)