In [1]:
from main_class import *
from layers import *
from loss_functions import *

In [2]:
md=NeuralNetwork(CrossEntropy)
md.add(Dense(5, input_shape=(3,)))
md.add(Activation('relu'))
md.add(Dense(1))
md.add(Activation('sigmoid'))

In [3]:
print(md.layers[0].W)

[[ 0.05865637  0.2403484  -0.24144241]
 [ 0.01250264  0.45373606  0.45759984]
 [-0.43233684 -0.33804681 -0.51792106]
 [-0.06834691 -0.54285219 -0.0498447 ]
 [ 0.17221671 -0.25578085  0.20352163]]


In [4]:
 md.layers[0].input_shape , md.layers[0].n_units ,md.layers[0].trainable 


((3,), 5, True)

In [5]:
 md.layers[1].input_shape 

(5,)

In [6]:
 md.layers[2].input_shape , md.layers[2].n_units 

((5,), 1)

In [7]:
print(md.layers[2].W)

[[ 0.04543503  0.18617307 -0.18702049  0.0096845   0.35146244]]


In [8]:
md.layers[0].layer_input

In [9]:
X= np.random.uniform(0, 1, (3,1))
X

array([[0.89629309],
       [0.12558531],
       [0.20724288]])

In [10]:
 md.layers[0].W

array([[ 0.05865637,  0.2403484 , -0.24144241],
       [ 0.01250264,  0.45373606,  0.45759984],
       [-0.43233684, -0.33804681, -0.51792106],
       [-0.06834691, -0.54285219, -0.0498447 ],
       [ 0.17221671, -0.25578085,  0.20352163]])

In [11]:
 md._forward(X)

AttributeError: 'Dense' object has no attribute 'forward_pass'