In [1]:
from main_class import *
from layers import *

In [2]:
md=NeuralNetwork()

In [3]:
md.add(Dense(5, input_shape=(3,)))

In [4]:
md.layers

In [5]:
md.add(Dense(15))

In [6]:
print(md.layers[0].W)

[[ 0.05865637  0.2403484  -0.24144241]
 [ 0.01250264  0.45373606  0.45759984]
 [-0.43233684 -0.33804681 -0.51792106]
 [-0.06834691 -0.54285219 -0.0498447 ]
 [ 0.17221671 -0.25578085  0.20352163]]


In [7]:
 md.layers[0].input_shape , md.layers[0].n_units ,md.layers[0].trainable 


((3,), 5, True)

In [8]:
 md.layers[1].input_shape , md.layers[1].n_units 

((5,), 15)

In [9]:
print(md.layers[1].W)

[[ 0.04543503  0.18617307 -0.18702049  0.0096845   0.35146244]
 [ 0.35445531 -0.33488668 -0.26184993 -0.40117993 -0.05294129]
 [-0.4204915  -0.03860954  0.13339849 -0.198127    0.15764718]
 [ 0.08127017 -0.42576355  0.0526407  -0.21533116 -0.0759358 ]
 [-0.19362105  0.17274781 -0.05325981 -0.30690682  0.0399353 ]
 [ 0.25072115 -0.17319372 -0.24868843 -0.10020155  0.3903134 ]
 [ 0.42574325  0.15418465  0.36030578  0.30924898 -0.10912545]
 [-0.3647322   0.13721488  0.05173435 -0.12382024 -0.24591873]
 [-0.08361113 -0.02778069 -0.20640197 -0.1862262  -0.03784643]
 [ 0.32247134  0.07714694 -0.19365434 -0.19858296 -0.04058725]
 [-0.263489   -0.267095    0.01255334 -0.36919328 -0.01468155]
 [-0.12327334  0.18576056  0.22069653  0.17091871  0.16920811]
 [-0.11305549  0.15038434 -0.14324371  0.06510882 -0.15580281]
 [-0.04906376 -0.39218045 -0.2301581   0.42181419 -0.24097281]
 [ 0.17126269  0.13459059  0.20029726 -0.02228142  0.08645871]]


In [10]:
md.layers[0].layer_input

In [18]:
A_prev= np.random.uniform(1, 1, (3,1))
A_prev

array([[1.],
       [1.],
       [1.]])

In [19]:
 md.layers[0].W

array([[ 0.05865637,  0.2403484 , -0.24144241],
       [ 0.01250264,  0.45373606,  0.45759984],
       [-0.43233684, -0.33804681, -0.51792106],
       [-0.06834691, -0.54285219, -0.0498447 ],
       [ 0.17221671, -0.25578085,  0.20352163]])

In [22]:
 md.layers[0].forward_linear(A_prev)

array([[ 0.05756236],
       [ 0.92383854],
       [-1.28830471],
       [-0.6610438 ],
       [ 0.11995749]])