In [3]:
from main_class import *
from layers import *
from loss_functions import *

In [4]:
md=NeuralNetwork(CrossEntropy)
md.add(Dense(5, input_shape=(3,)))
md.add(Activation('relu'))
md.add(Dense(1))
md.add(Activation('sigmoid'))

In [5]:
print(md.layers[0].W)

[[ 0.05865637  0.2403484  -0.24144241]
 [ 0.01250264  0.45373606  0.45759984]
 [-0.43233684 -0.33804681 -0.51792106]
 [-0.06834691 -0.54285219 -0.0498447 ]
 [ 0.17221671 -0.25578085  0.20352163]]


In [10]:
 md.layers[0].input_shape , md.layers[0].n_units ,md.layers[0].trainable 


((3,), 5, True)

In [7]:
 md.layers[1].input_shape 

(5,)

In [11]:
 md.layers[2].input_shape , md.layers[2].n_units 

((5,), 1)

In [12]:
print(md.layers[2].W)

[[ 0.04543503  0.18617307 -0.18702049  0.0096845   0.35146244]]


In [13]:
md.layers[0].layer_input

In [14]:
A_prev= np.random.uniform(1, 1, (3,1))
A_prev

array([[1.],
       [1.],
       [1.]])

In [15]:
 md.layers[0].W

array([[ 0.05865637,  0.2403484 , -0.24144241],
       [ 0.01250264,  0.45373606,  0.45759984],
       [-0.43233684, -0.33804681, -0.51792106],
       [-0.06834691, -0.54285219, -0.0498447 ],
       [ 0.17221671, -0.25578085,  0.20352163]])

In [16]:
 md.layers[0].forward_linear(A_prev)

array([[ 0.05756236],
       [ 0.92383854],
       [-1.28830471],
       [-0.6610438 ],
       [ 0.11995749]])