In [1]:
from main_class import *
from layers import *
from loss_functions import *

In [2]:
md=NeuralNetwork(CrossEntropy)
md.add(Dense(5, input_shape=(3,)))
md.add(Activation('relu'))
md.add(Dense(2))
md.add(Activation('sigmoid'))

In [3]:
print(md.layers[0].W)

[[ 0.05865637  0.2403484  -0.24144241]
 [ 0.01250264  0.45373606  0.45759984]
 [-0.43233684 -0.33804681 -0.51792106]
 [-0.06834691 -0.54285219 -0.0498447 ]
 [ 0.17221671 -0.25578085  0.20352163]]


In [4]:
 md.layers[0].input_shape , md.layers[0].n_units ,md.layers[0].trainable 


((3,), 5, True)

In [5]:
 md.layers[1].input_shape 

(5,)

In [6]:
 md.layers[2].input_shape , md.layers[2].n_units 

((5,), 2)

In [7]:
print(md.layers[2].W)

[[ 0.04543503  0.18617307 -0.18702049  0.0096845   0.35146244]
 [ 0.35445531 -0.33488668 -0.26184993 -0.40117993 -0.05294129]]


In [8]:
md.layers[0].layer_input

In [9]:
X= np.random.uniform(0, 1, (3,1))
X

array([[0.02987621],
       [0.45683322],
       [0.64914405]])

In [10]:
 AL=md._forward(X)
AL

array([[0.52526243],
       [0.45757748]])

In [11]:
md._backward(AL)

In [12]:
print(md.layers[0].W)

[[ 0.05865637  0.2403484  -0.24144241]
 [ 0.0125057   0.45378282  0.45766629]
 [-0.43233684 -0.33804681 -0.51792106]
 [-0.06834691 -0.54285219 -0.0498447 ]
 [ 0.17220774 -0.25591798  0.20332678]]
