In [1]:
from main_class import *
from layers import *
from loss_functions import *

In [2]:

#Initialization debugged



n_x = 3     # num_px * num_px * 3
n_h1 = 4
n_h2 = 7
n_y = 1

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)

md.add(Dense(n_h1, input_shape=(n_x,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_y, initializer = 'ng'))
md.add(Activation('sigmoid'))

print(md.layers[0].W,'\n\n' , md.layers[2].W)
#md.layers[2].W=np.array([[ 0.81217268, -0.30587821, -0.26408588, -0.53648431]])

[[ 0.93781623 -0.35319773 -0.3049401 ]
 [-0.61947872  0.49964333 -1.32879399]
 [ 1.00736754 -0.43948301  0.18419731]
 [-0.14397405  0.84414841 -1.18942279]] 

 [[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.0862141  -0.43892921  0.02110687  0.29140761]
 [-0.55030959  0.57236185  0.45079536  0.25124717]
 [ 0.45042797 -0.34186393 -0.06144511 -0.46788472]
 [-0.13394404  0.26517773 -0.34583038 -0.19837676]
 [-0.34358635 -0.42260282 -0.33562307 -0.0063323 ]
 [-0.55865517  0.11720785  0.82990109  0.37102208]]


In [3]:
np.random.seed(1)
X= np.random.uniform(0, 1, (n_x,1))
X

array([[4.17022005e-01],
       [7.20324493e-01],
       [1.14374817e-04]])

In [4]:
 AL=md._forward(X)
AL

array([[0.48340483]])

In [5]:
Y= np.array([[1]])

md.train_on_batch(X,Y)

(0.7269008277074714, 0.0)

In [6]:
md.layers[2].dW

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.02368126,  0.01757697,  0.01794578,  0.09495585],
       [ 0.01993361,  0.01479534,  0.0151058 ,  0.07992872],
       [-0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.00509348, -0.00378054, -0.00385987, -0.02042356]])

In [7]:
train_x=np.loadtxt('./data/train_x.csv', delimiter=",")
train_y=np.loadtxt('./data/train_y.csv', delimiter=",")

test_x=np.loadtxt('./data/test_x.csv', delimiter=",")
test_y=np.loadtxt('./data/test_y.csv', delimiter=",")

In [8]:
n_x = 12288     # num_px * num_px * 3
n_h1 = 20
n_h2 = 7
n_h3 = 5
n_y = 1

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)

md.add(Dense(n_h1, input_shape=(n_x,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h3, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_y, initializer = 'ng'))
md.add(Activation('sigmoid'))


In [9]:
AL=md._forward(train_x)
AL

array([[0.55893222, 0.58946891, 0.6117565 , 0.52893672, 0.63110697,
        0.58264379, 0.55652116, 0.50163581, 0.56419673, 0.54498116,
        0.60895365, 0.61711872, 0.59900556, 0.63670604, 0.59071161,
        0.70225162, 0.58916264, 0.67616388, 0.60341067, 0.5743451 ,
        0.60422171, 0.5768078 , 0.64351136, 0.6600246 , 0.66032722,
        0.53392824, 0.62094069, 0.5850552 , 0.5801449 , 0.59830082,
        0.56988221, 0.65897529, 0.58262912, 0.66742252, 0.59293297,
        0.55231835, 0.55894744, 0.55363025, 0.51792745, 0.6199034 ,
        0.61203414, 0.5789821 , 0.63664657, 0.62345464, 0.56825509,
        0.55307803, 0.64356209, 0.58381627, 0.60326641, 0.57609804,
        0.64855074, 0.5867378 , 0.60971581, 0.61903345, 0.56811604,
        0.62251748, 0.57811722, 0.64820438, 0.54374214, 0.54747803,
        0.55780033, 0.59000156, 0.5946332 , 0.57453264, 0.6150257 ,
        0.5559803 , 0.61366413, 0.54613142, 0.60085496, 0.59572995,
        0.62497464, 0.53557741, 0.54208569, 0.59

In [10]:
train_y = train_y.reshape(AL.shape)

In [11]:
md.layers[0].W.shape, md.layers[2].W.shape, md.layers[4].W.shape, md.layers[6].W.shape

((20, 12288), (7, 20), (5, 7), (1, 5))

In [12]:
md.layers[0].layer_input.shape, \
md.layers[0].W.shape,\
md.layers[1].layer_input.shape,\
md.layers[2].layer_input.shape


((12288, 209), (20, 12288), (20, 209), (20, 209))

In [13]:
md.layers[2].layer_input.shape, \
md.layers[2].W.shape,\
md.layers[3].layer_input.shape,\
md.layers[4].layer_input.shape

((20, 209), (7, 20), (7, 209), (7, 209))

In [14]:
md.layers[4].layer_input.shape, \
md.layers[4].W.shape,\
md.layers[5].layer_input.shape,\
md.layers[6].layer_input.shape

((7, 209), (5, 7), (5, 209), (5, 209))

In [15]:
md.layers[6].layer_input.shape, \
md.layers[6].W.shape,\
md.layers[7].layer_input.shape


((5, 209), (1, 5), (1, 209))

In [16]:
md.train_on_batch(train_x, train_y)

(0.7717493284237686, 0.3444976076555024)

In [17]:
md.layers[0].dW

array([[ 0.02223127,  0.02694779,  0.02155859, ...,  0.02135189,
         0.02459546,  0.01567405],
       [-0.01355345, -0.01592918, -0.01203554, ..., -0.01306601,
        -0.0151908 , -0.01004365],
       [ 0.00479684,  0.00557402,  0.00469332, ...,  0.00832289,
         0.00841248,  0.00630558],
       ...,
       [ 0.02225063,  0.02673607,  0.02145785, ...,  0.01882232,
         0.02287784,  0.01432669],
       [ 0.00064784,  0.00075776,  0.00101064, ...,  0.00023422,
         0.00059833,  0.00039404],
       [-0.01321156, -0.01627463, -0.01295946, ..., -0.01232409,
        -0.01437568, -0.00954212]])

In [18]:
train_x.shape[1]

209

In [19]:
train, val = md.fit(train_x, train_y, n_epochs=2400, batch_size=209)

100%|██████████| 2400/2400 [00:24<00:00, 98.83it/s] 


In [20]:
train[-1]

0.07178487334418722

In [21]:
pred =md.predict(train_x)
pred=(pred >0.5)

In [22]:
np.sum((pred == train_y)/209)

0.9904306220095692

In [23]:
train_x.shape , train_y.shape 

((12288, 209), (1, 209))

In [24]:
test_y = test_y.reshape((1, 50))

In [25]:
md.test_on_batch(test_x, test_y)

(0.7100303785501941, 0.8)

In [26]:
pred_test =md.predict(test_x)>=0.5
np.sum((pred_test == test_y)/50)

0.8