In [1]:
import numpy as np
from activation_functions import Softmax

In [2]:
test_matrix = np.random.rand(5,3)
test_matrix.shape

(5, 3)

In [3]:
soft = Softmax()

In [4]:
answer = soft(test_matrix) 
np.sum(answer,axis = 0, keepdims=True), np.sum(answer,axis = 0, keepdims=True).shape, \
(answer.shape) == test_matrix.shape, test_matrix.shape 

(array([[1., 1., 1.]]), (1, 3), True, (5, 3))

In [5]:
soft.gradient(test_matrix).shape

(5, 5, 3)

In [6]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(0,1), :] =displaced[np.arange(0,1), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,0,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(2,3), :] =displaced[np.arange(2,3), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,2,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
from loss_functions import MultiClassCrossEntropy

In [9]:
import numpy as np
nb_classes = 5
n_batch = 3
targets = np.array([[0, n_batch,0]]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets].T
test_AL = soft(np.random.random((nb_classes,n_batch)))

In [10]:
-np.sum(one_hot_targets * np.log(test_AL) ,axis= 0,keepdims=True) 

array([[1.62771427, 1.44374586, 1.4829122 ]])

In [11]:
multi  = MultiClassCrossEntropy()

In [12]:
final = np.sum( np.multiply( multi.gradient(one_hot_targets , soft(test_AL) ),soft.gradient(test_AL) , 
                           ), axis=1)
final

array([[-0.266921  ,  0.06143812, -0.26489558],
       [ 0.06596921,  0.07017512,  0.0662238 ],
       [ 0.0646736 ,  0.06273615,  0.06619103],
       [ 0.06804561, -0.26433317,  0.07006859],
       [ 0.06823258,  0.06998379,  0.06241216]])

In [13]:
multi.loss(one_hot_targets , soft(test_AL))

array([[0.5377534 , 0.52501139, 0.52773947]])

In [14]:
from loss_functions import SoftmaxCrossEntropy

In [15]:
softmulti = SoftmaxCrossEntropy()
softmulti.loss(one_hot_targets , test_AL)

array([0.5377534 , 0.52501139, 0.52773947])

In [16]:
softmulti.gradient(one_hot_targets , test_AL)

array([[-0.266921  ,  0.06143812, -0.26489558],
       [ 0.06596921,  0.07017512,  0.0662238 ],
       [ 0.0646736 ,  0.06273615,  0.06619103],
       [ 0.06804561, -0.26433317,  0.07006859],
       [ 0.06823258,  0.06998379,  0.06241216]])

In [17]:
Delta= 0.000000001
displaced = np.zeros(test_AL.shape)
displaced[:,:] = test_AL
displaced[np.arange(0,1), :] = displaced[np.arange(0,1), :]  + Delta
(softmulti.loss(one_hot_targets , displaced) - softmulti.loss(one_hot_targets , test_AL))/Delta

array([-0.26692082,  0.06143819, -0.26489566])

In [18]:
from layers import Activation_SoftMax

In [19]:
actsoft = Activation_SoftMax()

In [20]:
actsoft.forward(test_AL)

array([[0.199237  , 0.18431436, 0.20531325],
       [0.19790762, 0.21052536, 0.19867141],
       [0.19402079, 0.18820844, 0.19857308],
       [0.20413684, 0.20700048, 0.21020578],
       [0.20469774, 0.20995136, 0.18723648]])

In [21]:
actsoft.backward(multi.gradient(one_hot_targets , soft(test_AL) )) 

array([[-0.266921  ,  0.06143812, -0.26489558],
       [ 0.06596921,  0.07017512,  0.0662238 ],
       [ 0.0646736 ,  0.06273615,  0.06619103],
       [ 0.06804561, -0.26433317,  0.07006859],
       [ 0.06823258,  0.06998379,  0.06241216]])