In [1]:
import numpy as np
from activation_functions import Softmax

In [2]:
test_matrix = np.random.rand(5,3)
test_matrix.shape

(5, 3)

In [3]:
soft = Softmax()

In [4]:
answer = soft(test_matrix) 
np.sum(answer,axis = 0, keepdims=True), np.sum(answer,axis = 0, keepdims=True).shape, \
(answer.shape) == test_matrix.shape, test_matrix.shape 

(array([[1., 1., 1.]]), (1, 3), True, (5, 3))

In [5]:
soft.gradient(test_matrix).shape

(5, 5, 3)

In [6]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(0,1), :] =displaced[np.arange(0,1), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,0,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(2,3), :] =displaced[np.arange(2,3), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,2,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
from loss_functions import MultiClassCrossEntropy

In [9]:
import numpy as np
nb_classes = 5
n_batch = 3
targets = np.array([[0, n_batch,0]]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets].T
test_AL = soft(np.random.random((nb_classes,n_batch)))

In [10]:
-np.sum(one_hot_targets * np.log(test_AL) ,axis= 0,keepdims=True) 

array([[1.50469337, 1.99580663, 1.32651123]])

In [11]:
multi  = MultiClassCrossEntropy()

In [12]:
final = np.sum( np.multiply( multi.gradient(one_hot_targets , soft(test_AL) ),soft.gradient(test_AL) , 
                           ), axis=1)
final

array([[-0.26529512,  0.07489041, -0.26232969],
       [ 0.06190002,  0.06222895,  0.07335135],
       [ 0.07090575,  0.06991597,  0.06279752],
       [ 0.07028716, -0.27097486,  0.06183378],
       [ 0.06220218,  0.06393953,  0.06434704]])

In [13]:
multi.loss(one_hot_targets , soft(test_AL))

array([[0.52969114, 0.55874783, 0.51547058]])

In [14]:
from loss_functions import SoftmaxCrossEntropy

In [15]:
softmulti = SoftmaxCrossEntropy()
softmulti.loss(one_hot_targets , test_AL)

array([0.52969114, 0.55874783, 0.51547058])

In [16]:
softmulti.gradient(one_hot_targets , test_AL)

array([[-0.26529512,  0.07489041, -0.26232969],
       [ 0.06190002,  0.06222895,  0.07335135],
       [ 0.07090575,  0.06991597,  0.06279752],
       [ 0.07028716, -0.27097486,  0.06183378],
       [ 0.06220218,  0.06393953,  0.06434704]])

In [17]:
Delta= 0.000000001
displaced = np.zeros(test_AL.shape)
displaced[:,:] = test_AL
displaced[np.arange(0,1), :] = displaced[np.arange(0,1), :]  + Delta
(softmulti.loss(one_hot_targets , displaced) - softmulti.loss(one_hot_targets , test_AL))/Delta

array([-0.26529512,  0.07489032, -0.26232971])

In [18]:
from layers import Activation_SoftMax

In [19]:
actsoft = Activation_SoftMax()

In [20]:
actsoft.forward(test_AL)

array([[0.20411465, 0.22467124, 0.21301094],
       [0.18570006, 0.18668685, 0.22005404],
       [0.21271725, 0.20974792, 0.18839256],
       [0.21086149, 0.18707541, 0.18550133],
       [0.18660655, 0.19181858, 0.19304112]])

In [21]:
actsoft.backward(multi.gradient(one_hot_targets , soft(test_AL) )) 

array([[-0.26529512,  0.07489041, -0.26232969],
       [ 0.06190002,  0.06222895,  0.07335135],
       [ 0.07090575,  0.06991597,  0.06279752],
       [ 0.07028716, -0.27097486,  0.06183378],
       [ 0.06220218,  0.06393953,  0.06434704]])