In [1]:
import numpy as np
from activation_functions import Softmax

In [2]:
test_matrix = np.random.rand(5,3)
test_matrix.shape

(5, 3)

In [3]:
soft = Softmax()

In [4]:
answer = soft(test_matrix) 
np.sum(answer,axis = 0, keepdims=True), np.sum(answer,axis = 0, keepdims=True).shape, \
(answer.shape) == test_matrix.shape, test_matrix.shape 

(array([[1., 1., 1.]]), (1, 3), True, (5, 3))

In [5]:
soft.gradient(test_matrix).shape

(5, 5, 3)

In [6]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(0,1), :] =displaced[np.arange(0,1), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,0,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(2,3), :] =displaced[np.arange(2,3), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,2,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
from loss_functions import MultiClassCrossEntropy

In [9]:
import numpy as np
nb_classes = 5
n_batch = 3
targets = np.array([[0, n_batch,0]]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets].T
test_AL = soft(np.random.random((nb_classes,n_batch)))

In [10]:
-np.sum(one_hot_targets * np.log(test_AL) ,axis= 0,keepdims=True) 

array([[1.56956374, 1.91164238, 1.3168633 ]])

In [11]:
multi  = MultiClassCrossEntropy()

In [12]:
final = np.sum ( soft.gradient(test_AL)* multi.gradient(one_hot_targets , soft(test_AL) ) , 
               axis=1)
final

array([[-0.7985358 ,  0.19148203, -0.78630696],
       [ 0.21312395,  0.21075133,  0.1942021 ],
       [ 0.18888502,  0.22124825,  0.21499826],
       [ 0.19411243, -0.81059086,  0.18875719],
       [ 0.2024144 ,  0.18710924,  0.18834941]])

In [13]:
multi.loss(one_hot_targets , soft(test_AL))

array([[1.60214358, 1.66384583, 1.5432147 ]])

In [14]:
from loss_functions import SoftmaxCrossEntropy

In [15]:
softmulti = SoftmaxCrossEntropy()
softmulti(one_hot_targets , test_AL)

array([1.60214358, 1.66384583, 1.5432147 ])

In [16]:
softmulti.gradient(one_hot_targets , test_AL)

array([[-0.7985358 ,  0.19148203, -0.78630696],
       [ 0.21312395,  0.21075133,  0.1942021 ],
       [ 0.18888502,  0.22124825,  0.21499826],
       [ 0.19411243, -0.81059086,  0.18875719],
       [ 0.2024144 ,  0.18710924,  0.18834941]])

In [17]:
Delta= 0.000000001
displaced = np.zeros(test_AL.shape)
displaced[:,:] = test_AL
displaced[np.arange(0,1), :] = displaced[np.arange(0,1), :]  + Delta
(softmulti(one_hot_targets , displaced) - softmulti(one_hot_targets , test_AL))/Delta

array([-0.7985359 ,  0.19148194, -0.78630702])