In [1]:
from main_class import *
from layers import *
from loss_functions import *

In [2]:

#Initialization debugged



n_x = 3     # num_px * num_px * 3
n_h1 = 4
n_h2 = 7
n_y = 1

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)

md.add(Dense(n_h1, input_shape=(n_x,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_y, initializer = 'ng'))
md.add(Activation('sigmoid'))

print(md.layers[0].W,'\n\n' , md.layers[2].W)
#md.layers[2].W=np.array([[ 0.81217268, -0.30587821, -0.26408588, -0.53648431]])

[[ 0.93781623 -0.35319773 -0.3049401 ]
 [-0.61947872  0.49964333 -1.32879399]
 [ 1.00736754 -0.43948301  0.18419731]
 [-0.14397405  0.84414841 -1.18942279]] 

 [[-0.1612086  -0.19202718  0.56688472 -0.54994563]
 [-0.0862141  -0.43892921  0.02110687  0.29140761]
 [-0.55030959  0.57236185  0.45079536  0.25124717]
 [ 0.45042797 -0.34186393 -0.06144511 -0.46788472]
 [-0.13394404  0.26517773 -0.34583038 -0.19837676]
 [-0.34358635 -0.42260282 -0.33562307 -0.0063323 ]
 [-0.55865517  0.11720785  0.82990109  0.37102208]]


In [3]:
np.random.seed(1)
X= np.random.uniform(0, 1, (n_x,1))
X

array([[4.17022005e-01],
       [7.20324493e-01],
       [1.14374817e-04]])

In [4]:
 AL=md._forward(X)
AL

array([[0.48340483]])

In [5]:
Y= np.array([[1]])

md.train_on_batch(X,Y)

(0.7269008277074714, 0.0)

In [6]:
md.layers[2].dW

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.02368126,  0.01757697,  0.01794578,  0.09495585],
       [ 0.01993361,  0.01479534,  0.0151058 ,  0.07992872],
       [-0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.00509348, -0.00378054, -0.00385987, -0.02042356]])

In [7]:
train_x=np.loadtxt('./data/train_x.csv', delimiter=",")
train_y=np.loadtxt('./data/train_y.csv', delimiter=",")

test_x=np.loadtxt('./data/test_x.csv', delimiter=",")
test_y=np.loadtxt('./data/test_y.csv', delimiter=",")

In [8]:
train_x.shape, train_y.shape

((12288, 209), (209,))

In [9]:
n_x = 12288     # num_px * num_px * 3
n_ah1 = 20
n_h2 = 7
n_h3 = 5
n_y = 1

md=NeuralNetwork(CrossEntropy)
np.random.seed(1)

md.add(Dense(n_h1, input_shape=(n_x,), initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h2, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_h3, initializer = 'ng'))
md.add(Activation('relu'))

md.add(Dense(n_y, initializer = 'ng'))
#md.add(Activation('sigmoid'))


In [10]:
AL=md._forward(train_x)
AL

array([[0.5       , 0.51070848, 0.51218048, 0.49967203, 0.5       ,
        0.51146416, 0.50101524, 0.51058529, 0.51925091, 0.5072821 ,
        0.51751845, 0.52343415, 0.51664199, 0.51336132, 0.51244192,
        0.54214359, 0.5270497 , 0.52328587, 0.50970981, 0.50117934,
        0.51295187, 0.50503642, 0.52097726, 0.52117334, 0.52463952,
        0.49866621, 0.50913296, 0.5024773 , 0.50475451, 0.50052679,
        0.51684893, 0.51441823, 0.52723747, 0.52248452, 0.51326758,
        0.5095538 , 0.50782313, 0.51225255, 0.50716967, 0.51708065,
        0.51151789, 0.50425373, 0.52860268, 0.51460512, 0.53428623,
        0.51433466, 0.51425723, 0.51494943, 0.50822296, 0.51473462,
        0.52349993, 0.51696485, 0.5087737 , 0.51992917, 0.51761822,
        0.52176028, 0.51495116, 0.52633402, 0.50147862, 0.51146124,
        0.50115343, 0.5156802 , 0.52230976, 0.51571544, 0.52113602,
        0.5127096 , 0.50890673, 0.50196803, 0.51923171, 0.51591168,
        0.51940064, 0.50971126, 0.51274363, 0.50

In [11]:
train_y = train_y.reshape(AL.shape)

In [12]:
md.layers[0].W.shape, md.layers[2].W.shape, md.layers[4].W.shape, md.layers[6].W.shape

((4, 12288), (7, 4), (5, 7), (1, 5))

In [13]:
md.layers[0].layer_input.shape, \
md.layers[0].W.shape,\
md.layers[1].layer_input.shape,\
md.layers[2].layer_input.shape


((12288, 209), (4, 12288), (4, 209), (4, 209))

In [14]:
md.layers[2].layer_input.shape, \
md.layers[2].W.shape,\
md.layers[3].layer_input.shape,\
md.layers[4].layer_input.shape

((4, 209), (7, 4), (7, 209), (7, 209))

In [15]:
md.layers[4].layer_input.shape, \
md.layers[4].W.shape,\
md.layers[5].layer_input.shape,\
md.layers[6].layer_input.shape

((7, 209), (5, 7), (5, 209), (5, 209))

In [16]:
md.layers[6].layer_input.shape, \
md.layers[6].W.shape,\
md.layers[7].layer_input.shape


((5, 209), (1, 5), (1, 209))

In [17]:
md.train_on_batch(train_x, train_y)

(0.701906864851638, 0.3588516746411483)

In [18]:
md.layers[2].dW .shape

(7, 4)

In [19]:
train_x.shape[1]

209

In [20]:
train, val = md.fit(train_x, train_y, n_epochs=2400, batch_size=32)

100%|██████████| 2400/2400 [01:10<00:00, 34.26it/s]


In [21]:
pred =md.predict(train_x)
pred=(pred >0.5)

In [22]:
np.mean((pred == train_y))

1.0

In [23]:
train_x.shape , train_y.shape 

((12288, 209), (1, 209))

In [24]:
test_y = test_y.reshape((1, 50))

In [25]:
md.test_on_batch(test_x, test_y)

(0.0462309875157962, 0.78)

In [26]:
pred_test =md.predict(test_x)>=0.5
np.mean((pred_test == test_y))

0.78