In [3]:
import numpy as np
import sys
sys.path.append('../../network')
from activation_functions import Softmax

In [4]:
test_matrix = np.random.rand(5,3)
test_matrix.shape

(5, 3)

In [5]:
soft = Softmax()

In [6]:
answer = soft(test_matrix) 
np.sum(answer,axis = 0, keepdims=True), np.sum(answer,axis = 0, keepdims=True).shape, \
(answer.shape) == test_matrix.shape, test_matrix.shape 

(array([[1., 1., 1.]]), (1, 3), True, (5, 3))

In [7]:
soft.gradient(test_matrix).shape

(5, 5, 3)

In [8]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(0,1), :] =displaced[np.arange(0,1), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,0,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
Delta= 0.000000001
displaced = np.zeros(test_matrix.shape)
displaced[:,:] = test_matrix
displaced[np.arange(2,3), :] =displaced[np.arange(2,3), :]  + Delta
((soft(displaced) -  soft(test_matrix)  )/Delta  ) [:,:]- \
( soft.gradient(test_matrix)   )[:,2,:] < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
from loss_functions import MultiClassCrossEntropy

In [11]:
import numpy as np
nb_classes = 5
n_batch = 3
targets = np.array([[0, n_batch,0]]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets].T
test_AL = soft(np.random.random((nb_classes,n_batch)))

In [12]:
-np.sum(one_hot_targets * np.log(test_AL) ,axis= 0,keepdims=True) 

array([[1.29152877, 1.5175221 , 1.58453953]])

In [13]:
multi  = MultiClassCrossEntropy()

In [14]:
final = np.sum( np.multiply( multi.gradient(one_hot_targets , soft(test_AL) ),soft.gradient(test_AL) , 
                           ), axis=1)
final

array([[-0.26164355,  0.07037374, -0.26645549],
       [ 0.0630033 ,  0.06570425,  0.06948649],
       [ 0.06605232,  0.06276548,  0.07258576],
       [ 0.06088062, -0.26541886,  0.06275296],
       [ 0.0717073 ,  0.06657538,  0.06163028]])

In [15]:
multi.loss(one_hot_targets , soft(test_AL))

array([[0.5122649 , 0.53029795, 0.53542508]])

In [16]:
from loss_functions import SoftmaxCrossEntropy

In [17]:
softmulti = SoftmaxCrossEntropy()
softmulti.loss(one_hot_targets , test_AL)

array([0.5122649 , 0.53029795, 0.53542508])

In [18]:
softmulti.gradient(one_hot_targets , test_AL)

array([[-0.26164355,  0.07037374, -0.26645549],
       [ 0.0630033 ,  0.06570425,  0.06948649],
       [ 0.06605232,  0.06276548,  0.07258576],
       [ 0.06088062, -0.26541886,  0.06275296],
       [ 0.0717073 ,  0.06657538,  0.06163028]])

In [19]:
Delta= 0.000000001
displaced = np.zeros(test_AL.shape)
displaced[:,:] = test_AL
displaced[np.arange(0,1), :] = displaced[np.arange(0,1), :]  + Delta
(softmulti.loss(one_hot_targets , displaced) - softmulti.loss(one_hot_targets , test_AL))/Delta

array([-0.26164348,  0.07037371, -0.26645552])

In [20]:
from layers import Activation_SoftMax

In [21]:
actsoft = Activation_SoftMax()

In [22]:
actsoft.forward(test_AL)

array([[0.21506936, 0.21112123, 0.20063354],
       [0.18900991, 0.19711276, 0.20845947],
       [0.19815695, 0.18829645, 0.21775727],
       [0.18264187, 0.20374341, 0.18825887],
       [0.2151219 , 0.19972614, 0.18489085]])

In [23]:
actsoft.backward(multi.gradient(one_hot_targets , soft(test_AL) )) 

array([[-0.26164355,  0.07037374, -0.26645549],
       [ 0.0630033 ,  0.06570425,  0.06948649],
       [ 0.06605232,  0.06276548,  0.07258576],
       [ 0.06088062, -0.26541886,  0.06275296],
       [ 0.0717073 ,  0.06657538,  0.06163028]])