In [1]:
from batcher import batcher
import numpy as np

In [2]:
X= np.random.rand(3,10)

In [3]:
test = batcher(X, batch_size = 1)

In [8]:
next(test)

array([[0.2601394 ],
       [0.05662774],
       [0.66407714]])

In [5]:
X

array([[0.43026762, 0.83402075, 0.2601394 , 0.71246679, 0.49361221,
        0.78085798, 0.92570172, 0.87136548, 0.82420474, 0.70572698],
       [0.05035712, 0.02216909, 0.05662774, 0.90242545, 0.93832922,
        0.94044503, 0.56301743, 0.99614426, 0.74318505, 0.66498867],
       [0.54260515, 0.07495685, 0.66407714, 0.75142937, 0.30759669,
        0.00310079, 0.50419868, 0.6378377 , 0.88899784, 0.738491  ]])

In [6]:
X[:,0]

array([0.43026762, 0.05035712, 0.54260515])